### ISSUE TITLE
Cryptomator-cli does not support newest vault version

### ISSUE THREAD

**Issue by AresSec** [cryptomator/cli#47] opened 2021-12-19 14:01 UTC
I've created a Cryptomator Vault with Cryptomator version 1.6.4. Now I want to automate mounting and my backup process with Cryptomator-cli and I get the following exception:

Exception in thread "main" org.cryptomator.cryptolib.api.UnsupportedVaultFormatException: Tried to open vault of version 999, but can only handle version 7
	at org.cryptomator.cryptolib.v1.CryptorProviderImpl.createFromKeyFile(CryptorProviderImpl.java:118)
	at org.cryptomator.cryptolib.v1.CryptorProviderImpl.createFromKeyFile(CryptorProviderImpl.java:109)
	at org.cryptomator.cryptolib.v1.CryptorProviderImpl.createFromKeyFile(CryptorProviderImpl.java:40)
	at org.cryptomator.cryptofs.CryptoFileSystemModule.provideCryptor(CryptoFileSystemModule.java:38)
	at org.cryptomator.cryptofs.CryptoFileSystemModule_ProvideCryptorFactory.provideCryptor(CryptoFileSystemModule_ProvideCryptorFactory.java:56)
	at org.cryptomator.cryptofs.CryptoFileSystemModule_ProvideCryptorFactory.get(CryptoFileSystemModule_ProvideCryptorFactory.java:43)
	at org.cryptomator.cryptofs.CryptoFileSystemModule_ProvideCryptorFactory.get(CryptoFileSystemModule_ProvideCryptorFactory.java:11)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.cryptomator.cryptofs.CryptoFileSystemImpl_Factory.get(CryptoFileSystemImpl_Factory.java:110)
	at org.cryptomator.cryptofs.CryptoFileSystemImpl_Factory.get(CryptoFileSystemImpl_Factory.java:16)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)

Operating System: macOS 11.3
Mount type: Fuse
Java: OpenJDK 17
Cryptomator App version: 1.6.4
Cryptomator-cli version: 0.4.0

**Comment by tobihagemann** [comment] 2021-12-19 18:04
Duplicate of #45

**Closed** 2021-12-19 18:04 UTC
Labels: duplicate

**Comment by AresSec** [comment] 2021-12-19 18:30
@tobihagemann, ah sorry, I didn't recognize the already existing one. Do you know of any timeline for the next release? The develop branch already has this implemented.

**Comment by tobihagemann** [comment] 2021-12-20 12:07
It's now available: https://github.com/cryptomator/cli/releases/tag/0.5.0
