### ISSUE TITLE
Feature request: add support for mounting FUSE instead of WebDAV

### ISSUE THREAD

**Issue by pongnguy** [cryptomator/cli#64] opened 2024-04-18 17:52 UTC
The current GUI client gives the option of mounting locally as FUSE or WebDAV.  However, the CLI only supports WebDAV.  I have found FUSE to be almost pain-free, whereas WebDAV is tricky to set up.  Any plans to add FUSE mount from CLI, or enabling mounting as FUSE from fstab?  This would greatly streamline interacting with encrypted files programmatically.

**Comment by SailReal** [comment] 2024-04-18 19:09
Fuse is supported since https://github.com/cryptomator/cli/pull/33, it is just not yet documented :sweat_smile:

Here you can see a usage example:
```
java -jar cryptomator-cli.jar \
  --vault demoVault=/home/julian/Downloads/Demo \
  --password demoVault=asdasdasd \
  --fusemount demoVault=/home/julian/Downloads/mount
```

**Comment by SailReal** [comment] 2024-04-19 10:48
Duplicate of #25

**Closed by SailReal** 2024-04-19 10:48 UTC
